### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rphlo** [NicoRio42/cassini#1]
You should define a better license.
The fact that this contains code from rust karttapullautin would suggest you use the GPL license...

**Comment by jenskastensson** [comment]
Hello,
thank you very much for this development, I'm really interested in trying Cassini out!
I have downloaded this tile  [linkto-ign.fr](https://storage.sbg.cloud.ovh.net/v1/AUTH_63234f509d6048bca3c9fd7928720ca1/ppk-lidar/RP/LHD_FXX_1015_6300_PTS_C_LAMB93_IGN69.copc.laz)
(Caussols, Alpes-Maritimes, France)

When I process the .laz file with Cassini under Windows, I'm getting a RT error, see below. 
What am I doing wrong here and how to troubleshoot it? (I've opted out for OSM data as it failed)

Best regards
Jens

```
(cassini) PS C:...Documents\Orienteering\Cassini> .\cassini.exe .\caussols\LHD_FXX_1015_6300_PTS_C_LAMB93_IGN69.copc.laz  --skip-vector
Executing PDAL pipeline -> Done in 179.3s
Rendering vegetation -> Done in 1.0s
Generating dem with bufferTraceback (most recent call last):
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\auxiliary\gdal_argparse.py", line 229, in main
    self.doit(**kwargs)
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\gdal_fillnodata.py", line 286, in doit
    return gdal_fillnodata(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\auxiliary\util.py", line 62, in enable_exceptions_wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\gdal_fillnodata.py", line 105, in gdal_fillnodata
    dst_ds = drv.Create(
             ^^^^^^^^^^^
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo\gdal.py", line 3742, in Create
    return _gdal.Driver_Create(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError

Traceback (most recent call last):
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\auxiliary\gdal_argparse.py", line 229, in main
    self.doit(**kwargs)
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\gdal_fillnodata.py", line 286, in doit
    return gdal_fillnodata(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\auxiliary\util.py", line 62, in enable_exceptions_wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo_utils\gdal_fillnodata.py", line 105, in gdal_fillnodata
    dst_ds = drv.Create(
             ^^^^^^^^^^^
  File "C:\...\miniconda3\envs\cassini\Lib\site-packages\osgeo\gdal.py", line 3742, in Create
    return _gdal.Driver_Create(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError

 -> Done in 3.0s
Generating countours shapefiles -> Done in 145.8ms
Generating slopes tif image -> Done in 336.5ms
Smoothing contours -> Done in 46.8ms
Culling formlines and rendering contours -> Done in 236.2ms
Rendering cliffs -> Done in 276.9ms
Rendering map to png -> Done in 810.8ms
Tile generated in 185.1s
```

**Comment by NicoRio42** [comment]
Sorry for the late answer, I have been working on other projects this September and my Github notifications seems broken...
Indeed, I just changed the licence to GPL.
